(()=>{'use strict';const $=s=>document.querySelector(s);const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());const next=d=>new Date(Date.parse(d+'T12:00:00Z')+86400000).toISOString().slice(0,10);const quick=$('#quick-reservation'),form=$('#reservaForm'),dialog=$('#reservation-dialog');$('#year').textContent=String(new Date().getFullYear());
for(const f of [quick,form]){f.elements.checkin.min=today;f.elements.checkin.value=today;f.elements.checkout.min=next(today);f.elements.checkout.value=next(today);f.elements.checkin.addEventListener('change',()=>{const d=f.elements.checkin.value;if(!d)return;f.elements.checkout.min=next(d);if(f.elements.checkout.value<=d)f.elements.checkout.value=next(d);});}
function openReservation(room){const dates=new FormData(quick);for(const key of ['checkin','checkout','guests'])form.elements[key].value=dates.get(key);form.elements.checkin.min=today;form.elements.checkout.min=next(form.elements.checkin.value);form.elements.room.value=room||'A definir';$('.form-error').hidden=true;dialog.showModal();}
quick.addEventListener('submit',e=>{e.preventDefault();if(quick.reportValidity())openReservation();});document.querySelectorAll('.room-reserve').forEach(b=>b.addEventListener('click',()=>openReservation(b.dataset.room)));
form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);if(String(d.get('checkin'))<today||String(d.get('checkout'))<=String(d.get('checkin'))){$('.form-error').textContent='Confira as datas de entrada e saída.';$('.form-error').hidden=false;return;}const date=s=>s.split('-').reverse().join('/');const message=['Olá! Gostaria de consultar uma estadia no Teles Plaza Hotel.','','Nome: '+String(d.get('name')).trim(),'Entrada: '+date(String(d.get('checkin'))),'Saída: '+date(String(d.get('checkout'))),'Hóspedes: '+d.get('guests'),'Acomodação: '+d.get('room'),d.get('notes')?'Observações: '+String(d.get('notes')).trim():''].filter(Boolean).join('\n');window.open('https://wa.me/5561999343604?text='+encodeURIComponent(message),'_blank','noopener');});
const menu=$('.menu-toggle'),nav=$('#navigation');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');nav.classList.toggle('open',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});});
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{const p=$('#photo-dialog');p.querySelector('img').src=b.dataset.photo;p.querySelector('img').alt=b.dataset.caption;$('#photo-caption').textContent=b.dataset.caption;p.showModal();}));$('#privacy-button').addEventListener('click',()=>$('#privacy-dialog').showModal());
const theme=$('.theme-toggle');function setTheme(dark){document.documentElement.dataset.theme=dark?'dark':'light';theme.setAttribute('aria-pressed',String(dark));theme.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro');theme.querySelector('use').setAttribute('href',dark?'#sun':'#moon');}try{setTheme(localStorage.getItem('teles-theme')==='dark');}catch{}theme.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';setTheme(dark);try{localStorage.setItem('teles-theme',dark?'dark':'light');}catch{}});

const slides=[...document.querySelectorAll('.hero-slide')],carousel=$('.hero-carousel'),pause=$('.carousel-pause');let slide=0,timer=null,paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function show(n){slide=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.hidden=i!==slide);$('.slide-counter').textContent=String(slide+1).padStart(2,'0')+' / 02';$('.slide-label').textContent=slide===0?'Sua estadia em Águas Lindas':'Traslados e van executiva';}function stop(){clearInterval(timer);timer=null;}function start(){stop();if(!paused&&!document.hidden)timer=setInterval(()=>show(slide+1),7000);}function paintPause(){pause.textContent=paused?'Reproduzir':'Pausar';pause.setAttribute('aria-label',paused?'Iniciar alternância das imagens':'Pausar alternância das imagens');}pause.addEventListener('click',()=>{paused=!paused;paintPause();start();});$('.carousel-prev').addEventListener('click',()=>{show(slide-1);paused=true;paintPause();stop();});$('.carousel-next').addEventListener('click',()=>{show(slide+1);paused=true;paintPause();stop();});carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',start);carousel.addEventListener('focusin',stop);carousel.addEventListener('focusout',e=>{if(!carousel.contains(e.relatedTarget))start();});document.addEventListener('visibilitychange',()=>document.hidden?stop():start());paintPause();start();
})();
