(()=>{'use strict';const $=s=>document.querySelector(s);const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());const bookingFrom=today<'2026-10-05'?'2026-10-05':today;const next=d=>new Date(Date.parse(d+'T12:00:00Z')+86400000).toISOString().slice(0,10);const quick=$('#quick-reservation'),form=$('#reservaForm'),dialog=$('#reservation-dialog');$('#year').textContent=String(new Date().getFullYear());
for(const f of [quick,form]){f.elements.checkin.min=bookingFrom;f.elements.checkin.value=bookingFrom;f.elements.checkout.min=next(bookingFrom);f.elements.checkout.value=next(bookingFrom);f.elements.checkin.addEventListener('change',()=>{const d=f.elements.checkin.value;if(!d)return;f.elements.checkout.min=next(d);if(f.elements.checkout.value<=d)f.elements.checkout.value=next(d);});}
const bookingAPI='https://kukhsxcaqcywsvbkwhrm.supabase.co/functions/v1/hotel-api';let requestId='',availabilityRun=0;
async function availability(){const run=++availabilityRun;const status=$('#availability-status'),select=form.elements.room;select.replaceChildren(new Option('Consultando…',''));form.querySelector('[type="submit"]').disabled=true;status.textContent='Consultando disponibilidade…';try{const params=new URLSearchParams({checkin:form.elements.checkin.value,checkout:form.elements.checkout.value,guests:form.elements.guests.value});const r=await fetch(bookingAPI+'/availability?'+params);const d=await r.json();if(run!==availabilityRun)return;if(!r.ok)throw new Error(d.error);select.replaceChildren();for(const c of d.categories){const rate=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c.rate/100);select.add(new Option(c.category+' · a partir de '+rate+'/diária',c.category));}if(Number(form.elements.guests.value)>=5){select.add(new Option('Hospedagem para grupo','Grupo'));status.textContent='A recepção vai organizar os quartos necessários para o seu grupo.';}else status.textContent=d.categories.length?'Escolha a acomodação. A confirmação depende da recepção.':'Nenhuma opção disponível on-line nessas datas. Fale com a recepção pelo WhatsApp.';form.querySelector('[type="submit"]').disabled=!select.options.length;}catch(e){if(run!==availabilityRun)return;select.replaceChildren(new Option('Indisponível no momento',''));status.textContent=e.message+' Você também pode consultar pelo WhatsApp.';}}
function openReservation(){const dates=new FormData(quick);for(const key of ['checkin','checkout','guests'])form.elements[key].value=dates.get(key);form.elements.checkin.min=bookingFrom;form.elements.checkout.min=next(form.elements.checkin.value);$('.form-error').hidden=true;$('#request-success').hidden=true;form.querySelector('[type="submit"]').textContent='Enviar solicitação';requestId=crypto.randomUUID();dialog.showModal();availability();}
quick.addEventListener('submit',e=>{e.preventDefault();if(quick.reportValidity())openReservation();});document.querySelectorAll('.room-reserve').forEach(b=>b.addEventListener('click',openReservation));for(const key of ['checkin','checkout','guests'])form.elements[key].addEventListener('change',()=>{requestId=crypto.randomUUID();$('#request-success').hidden=true;availability();});
form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type="submit"]');button.disabled=true;$('.form-error').hidden=true;try{const d=Object.fromEntries(new FormData(form));const r=await fetch(bookingAPI+'/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,id:requestId,category:d.room})});const data=await r.json();if(!r.ok)throw new Error(data.error);$('#request-success').textContent=data.message+' Protocolo: '+data.id.slice(0,8).toUpperCase();$('#request-success').hidden=false;button.textContent='Solicitação enviada';}catch(e){$('.form-error').textContent=e.message;$('.form-error').hidden=false;button.disabled=false;}});
const menu=$('.menu-toggle'),nav=$('#navigation');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');nav.classList.toggle('open',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});});
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{const p=$('#photo-dialog');p.querySelector('img').src=b.dataset.photo;p.querySelector('img').alt=b.dataset.caption;$('#photo-caption').textContent=b.dataset.caption;p.showModal();}));$('#privacy-button').addEventListener('click',()=>$('#privacy-dialog').showModal());
const theme=$('.theme-toggle');function setTheme(dark){document.documentElement.dataset.theme=dark?'dark':'light';theme.setAttribute('aria-pressed',String(dark));theme.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro');theme.querySelector('use').setAttribute('href',dark?'#sun':'#moon');}try{setTheme(localStorage.getItem('teles-theme')==='dark');}catch{}theme.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';setTheme(dark);try{localStorage.setItem('teles-theme',dark?'dark':'light');}catch{}});

const slides=[...document.querySelectorAll('.hero-slide')],carousel=$('.hero-carousel'),pause=$('.carousel-pause');let slide=0,timer=null,paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function show(n){slide=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.hidden=i!==slide);$('.slide-counter').textContent=String(slide+1).padStart(2,'0')+' / 02';$('.slide-label').textContent=slide===0?'Sua estadia em Águas Lindas':'Traslados e van executiva';}function stop(){clearInterval(timer);timer=null;}function start(){stop();if(!paused&&!document.hidden)timer=setInterval(()=>show(slide+1),7000);}function paintPause(){pause.textContent=paused?'Reproduzir':'Pausar';pause.setAttribute('aria-label',paused?'Iniciar alternância das imagens':'Pausar alternância das imagens');}pause.addEventListener('click',()=>{paused=!paused;paintPause();start();});$('.carousel-prev').addEventListener('click',()=>{show(slide-1);paused=true;paintPause();stop();});$('.carousel-next').addEventListener('click',()=>{show(slide+1);paused=true;paintPause();stop();});carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',start);carousel.addEventListener('focusin',stop);carousel.addEventListener('focusout',e=>{if(!carousel.contains(e.relatedTarget))start();});document.addEventListener('visibilitychange',()=>document.hidden?stop():start());paintPause();start();
})();
