'use client';
import {apiFetch} from '@/lib/client';
import {useCallback,useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Plus,RefreshCw,Download,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {money,addDays,type HotelData} from '@/lib/hotel-domain';
import {qty,type OperationsData,type Proposal} from '@/lib/operations-domain';
const labels:Record<string,string>={pending:'Pendente',approved:'Aprovada',received:'Recebida',cancelled:'Cancelada',draft:'Rascunho',sent:'Enviada'};
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Choice({name,options}:{name:string;options:[string,string][]}){return <Select name={name} required><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function exportCsv(name:string,rows:unknown[][]){const safe=(v:unknown)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function printProposal(p:Proposal,hotel:string){const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const win=window.open('','_blank');if(!win){toast.error('Permita abrir a proposta em uma nova janela.');return;}win.opener=null;win.document.write(`<!doctype html><html lang="pt-BR"><head><title>Proposta ${esc(p.client)}</title><style>body{font:15px Arial;color:#142b40;max-width:900px;margin:50px auto;padding:24px}h1{font:36px Georgia}table{width:100%;border-collapse:collapse;margin:30px 0}td,th{padding:12px 6px;text-align:left;border-bottom:1px solid #ddd}small{color:#526273}.total{text-align:right;font-size:24px}.terms{white-space:pre-wrap}button{padding:12px;cursor:pointer}@media print{button{display:none}}</style></head><body><small>${esc(hotel)}</small><h1>Proposta de hospedagem e serviços</h1><p><b>${esc(p.client)}</b><br>${esc(p.contact)}</p><p>Validade: ${esc(p.valid_until.split('-').reverse().join('/'))} · ${esc(labels[p.status])}</p><table><thead><tr><th>Descrição</th><th>Unidade</th><th>Qtd.</th><th>Dias</th><th>Valor unitário</th><th>Total</th></tr></thead><tbody>${p.items.map(i=>`<tr><td>${esc(i.description)}</td><td>${esc(i.unit)}</td><td>${i.quantity}</td><td>${i.days}</td><td>${money(i.rate)}</td><td>${money(i.total)}</td></tr>`).join('')}</tbody></table><p class="total"><b>Total ${money(p.total)}</b></p><p class="terms">${esc(p.terms)}</p><small>Proposta comercial sujeita à disponibilidade. A aprovação não cria uma reserva automaticamente.</small><p><button onclick="window.print()">Imprimir / salvar como PDF</button></p></body></html>`);win.document.close();}
export default function OperationsPanel({page,hotelData,onChanged}:{page:string;hotelData:HotelData;onChanged:()=>void}){
 const hotel=hotelData.hotel!,today=hotelData.today;
 const [data,setData]=useState<OperationsData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[actionId,setActionId]=useState(''),[lineCount,setLineCount]=useState(1),[month,setMonth]=useState(today.slice(0,7));
 const refresh=useCallback(async()=>{try{const r=await apiFetch('/api/operations?hotel='+encodeURIComponent(hotel.id),{cache:'no-store'});const d=await r.json() as OperationsData & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError((e as Error).message);}},[hotel.id]);
 useEffect(()=>{setData(null);void refresh();},[refresh]);
 const open=(s:string)=>{setActionId(crypto.randomUUID());setLineCount(1);setError('');setModal(s)};
 const mutate=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');try{const r=await apiFetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hotel:hotel.id,id:actionId,...payload})});const d=await r.json() as {error?:string;message:string};if(!r.ok)throw new Error(d.error);setModal('');await refresh();onChanged();toast.success(d.message);}catch(e){setError((e as Error).message);toast.error((e as Error).message);}finally{setBusy(false)}};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),b:Record<string,unknown>=Object.fromEntries(f);if(modal==='order')b.items=Array.from({length:lineCount},(_,i)=>({product:f.get('product'+i),quantity:f.get('quantity'+i),rate:f.get('rate'+i)}));if(modal==='proposal')b.items=Array.from({length:lineCount},(_,i)=>({description:f.get('description'+i),unit:f.get('unit'+i),quantity:f.get('quantity'+i),days:f.get('days'+i),rate:f.get('rate'+i)}));void mutate({...b,action:modal});};
 const table=(heads:string[],rows:ReactNode[][])=><Table><TableHeader><TableRow>{heads.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length?rows.map((r,i)=><TableRow key={i}>{r.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={heads.length}>Nenhum registro neste período.</TableCell></TableRow>}</TableBody></Table>;
 if(!data)return <section className="panel panel-padding"><p role={error?'alert':undefined}>{error||'Carregando registros…'}</p><button className="secondary" onClick={refresh}>Atualizar</button></section>;
 const shift=data.shifts.find(s=>!s.closed),entries=hotelData.entries.filter(e=>e.due.startsWith(month)&&e.kind!=='charge');
 return <><div className="filter-row no-panel"><p className="muted">{({stock:'Entradas, consumo e níveis mínimos por produto.',purchasing:'Cadastre fornecedores, aprove compras e registre o recebimento.',proposals:'Hospedagem, alimentação e transporte em uma proposta.',cash:'Conferência dos pagamentos e despesas em dinheiro.',reports:'Exporte os movimentos para conferência financeira.'} as Record<string,string>)[page]}</p><button className="secondary" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Atualizar</button></div>{error&&!modal&&<p className="form-error" role="alert">{error}</p>}
 {page==='stock'&&<><div className="heading-actions"><button className="primary" onClick={()=>open('product')}><Plus size={16}/>Cadastrar produto</button><button className="secondary" disabled={!data.products.length} onClick={()=>open('stock')}>Movimentar estoque</button></div><section className="panel">{table(['Produto','Categoria','Saldo','Mínimo','Situação'],data.products.map(p=>[<strong key={p.id}>{p.name}</strong>,p.category,qty(p.quantity)+' '+p.unit,qty(p.minimum)+' '+p.unit,p.quantity<=p.minimum?'Repor estoque':'Regular']))}</section><section className="panel"><div className="panel-heading"><h2>Últimas movimentações</h2></div>{table(['Produto','Quantidade','Motivo','Data'],data.movements.map(m=>[data.products.find(p=>p.id===m.product_id)?.name,qty(m.quantity),m.reason,new Date(m.created).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})]))}</section></>}
 {page==='purchasing'&&<><div className="heading-actions"><button className="primary" disabled={!data.suppliers.length||!data.products.length} onClick={()=>open('order')}><Plus size={16}/>Pedido de compra</button><button className="secondary" onClick={()=>open('supplier')}>Cadastrar fornecedor</button></div>{(!data.suppliers.length||!data.products.length)&&<p className="muted">Cadastre um fornecedor e os produtos na seção Estoque para criar pedidos.</p>}<section className="panel">{table(['Fornecedor','Itens','Total','Vencimento','Situação','Ações'],data.orders.map(o=>[data.suppliers.find(s=>s.id===o.supplier_id)?.name,o.items.map(i=>`${i.name}: ${qty(i.quantity)} ${i.unit}`).join('; '),money(o.total),o.due.split('-').reverse().join('/'),labels[o.status],<div key={o.id} className="inline-actions">{o.status==='pending'&&<><button disabled={busy} className="text-link" onClick={()=>mutate({action:'order_status',id:o.id,status:'approved'})}>Aprovar</button><button disabled={busy} className="text-link" onClick={()=>mutate({action:'order_status',id:o.id,status:'cancelled'})}>Cancelar</button></>}{o.status==='approved'&&<button disabled={busy} className="text-link" onClick={()=>mutate({action:'order_status',id:o.id,status:'received'})}>Receber mercadoria</button>}</div>]))}</section><p className="muted">O recebimento adiciona os produtos ao estoque e cria uma conta a pagar no Financeiro.</p><section className="panel"><div className="panel-heading"><h2>Fornecedores</h2></div>{table(['Nome','Documento','Contato','Observações'],data.suppliers.map(s=>[s.name,s.document,s.contact,s.notes]))}</section></>}
 {page==='proposals'&&<><div className="heading-actions"><button className="primary" onClick={()=>open('proposal')}><Plus size={16}/>Nova proposta</button></div><section className="panel">{table(['Cliente','Validade','Total','Situação','Ações'],data.proposals.map(p=>[p.client,p.valid_until.split('-').reverse().join('/'),money(p.total),labels[p.status],<div key={p.id} className="inline-actions"><button className="text-link" onClick={()=>printProposal(p,hotel.name)}><Printer size={16}/>Imprimir</button>{p.status==='draft'&&<button disabled={busy} className="text-link" onClick={()=>mutate({action:'proposal_status',id:p.id,status:'sent'})}>Marcar enviada</button>}{['draft','sent'].includes(p.status)&&<><button disabled={busy} className="text-link" onClick={()=>mutate({action:'proposal_status',id:p.id,status:'approved'})}>Aprovar</button><button disabled={busy} className="text-link" onClick={()=>mutate({action:'proposal_status',id:p.id,status:'cancelled'})}>Cancelar</button></>}</div>]))}</section><p className="muted">Envie a proposta ao cliente após conferir o documento. A aprovação comercial não bloqueia quartos; registre as reservas na seção Reservas.</p></>}
 {page==='cash'&&<><section className="panel settings-panel"><h2>{shift?'Caixa aberto':'Caixa fechado'}</h2><p>{shift?`Fundo inicial: ${money(shift.opening)} · Saldo esperado: ${money(shift.live_expected)}`:'Abra o caixa antes de registrar recebimentos ou despesas pagos em dinheiro.'}</p><button className="primary" onClick={()=>{open(shift?'close_shift':'open_shift');if(shift)setActionId(shift.id)}}>{shift?'Conferir e fechar':'Abrir caixa'}</button></section><section className="panel">{table(['Abertura','Responsável','Fundo','Esperado','Contado','Diferença','Situação'],data.shifts.map(s=>[new Date(s.opened).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}),s.actor,money(s.opening),money(s.closed?s.expected??0:s.live_expected),s.closed?money(s.counted??0):'—',s.closed?money((s.counted??0)-(s.expected??0)):'—',s.closed?'Fechado':'Aberto']))}</section><p className="muted">O caixa considera apenas os lançamentos em dinheiro vinculados à abertura. Pix, cartões e transferências ficam no Financeiro.</p></>}
 {page==='reports'&&<><div className="finance-toolbar"><Field label="Período"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><button className="secondary" onClick={()=>exportCsv('financeiro-'+month+'.csv',[['Data','Descrição','Tipo','Forma','Situação','Valor R$'],...entries.map(e=>[e.due,e.description,({payment:'Recebimento',refund:'Devolução',expense:'Despesa'} as Record<string,string>)[e.kind],e.method,e.paid?'Pago':'Pendente',(e.amount/100).toFixed(2)])])}><Download size={16}/>Exportar financeiro</button><button className="secondary" onClick={()=>exportCsv('estoque-'+today+'.csv',[['Produto','Categoria','Unidade','Saldo','Mínimo'],...data.products.map(p=>[p.name,p.category,p.unit,qty(p.quantity),qty(p.minimum)])])}>Exportar estoque</button></div><section className="panel">{table(['Forma','Recebimentos','Devoluções','Despesas pagas','Líquido'],['Pix','Dinheiro','Cartão de crédito','Cartão de débito','Transferência'].map(method=>{const sum=(kind:string)=>entries.filter(e=>e.method===method&&e.kind===kind&&e.paid).reduce((s,e)=>s+e.amount,0);return [method,money(sum('payment')),money(sum('refund')),money(sum('expense')),money(sum('payment')-sum('refund')-sum('expense'))]}))}</section><p className="muted">Relatório financeiro de caixa. A escrituração contábil e a emissão fiscal dependem de integração específica.</p></>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!busy&&!v)setModal('')}}><DialogContent className="hotel-dialog"><DialogHeader><DialogTitle>{({supplier:'Cadastrar fornecedor',product:'Cadastrar produto',stock:'Movimentar estoque',order:'Pedido de compra',proposal:'Nova proposta',open_shift:'Abrir caixa',close_shift:'Fechar caixa'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>Confira as informações antes de salvar.</DialogDescription></DialogHeader><form className="hotel-form" onSubmit={submit}>
 {modal==='supplier'&&<><Field label="Nome"><input name="name" required maxLength={200}/></Field><Field label="CNPJ / CPF"><input name="document" maxLength={30}/></Field><Field label="Contato"><input name="contact" maxLength={150}/></Field><Field label="Observações"><textarea name="notes" maxLength={1000}/></Field></>}
 {modal==='product'&&<><Field label="Produto"><input name="name" required maxLength={200}/></Field><Field label="Unidade"><Choice name="unit" options={['un','kg','L','pacote','caixa'].map(v=>[v,v])}/></Field><Field label="Categoria"><Choice name="category" options={['Alimentação','Limpeza','Frigobar','Enxoval','Manutenção','Outros'].map(v=>[v,v])}/></Field><Field label="Estoque mínimo"><input name="minimum" type="number" min="0" step="0.001" defaultValue="0" required/></Field></>}
 {modal==='stock'&&<><Field label="Produto"><Choice name="product" options={data.products.map(p=>[p.id,p.name+' ('+p.unit+')'])}/></Field><Field label="Movimento"><Choice name="kind" options={[["in","Entrada / ajuste positivo"],["out","Consumo / saída"]]}/></Field><Field label="Quantidade"><input name="quantity" type="number" min="0.001" step="0.001" required/></Field><Field label="Motivo"><input name="reason" required maxLength={200}/></Field></>}
 {modal==='order'&&<><Field label="Fornecedor"><Choice name="supplier" options={data.suppliers.map(s=>[s.id,s.name])}/></Field><Field label="Vencimento da conta"><input type="date" name="due" defaultValue={today} required/></Field>{Array.from({length:lineCount},(_,i)=><fieldset className="operation-line" key={i}><legend>Item {i+1}</legend><Field label="Produto"><Choice name={'product'+i} options={data.products.map(p=>[p.id,p.name+' ('+p.unit+')'])}/></Field><Field label="Quantidade"><input name={'quantity'+i} type="number" min="0.001" step="0.001" required/></Field><Field label="Preço por unidade (R$)"><input name={'rate'+i} type="number" min="0.01" step="0.01" required/></Field></fieldset>)}<Field label="Observações"><textarea name="notes" maxLength={1000}/></Field></>}
 {modal==='proposal'&&<><Field label="Cliente / empresa"><input name="client" maxLength={200} required/></Field><Field label="Contato"><input name="contact" maxLength={150}/></Field><Field label="Validade"><input type="date" name="validUntil" min={today} defaultValue={addDays(today,7)} required/></Field>{Array.from({length:lineCount},(_,i)=><fieldset className="operation-line" key={i}><legend>Item {i+1}</legend><Field label="Descrição"><input name={'description'+i} maxLength={200} required placeholder="Ex.: Hospedagem em quarto duplo"/></Field><Field label="Unidade"><Choice name={'unit'+i} options={['quarto/diária','pessoa/dia','veículo/diária','serviço'].map(v=>[v,v])}/></Field><div className="form-grid"><Field label="Quantidade"><input name={'quantity'+i} type="number" min="1" max="10000" defaultValue="1" required/></Field><Field label="Dias (serviço único: 1)"><input name={'days'+i} type="number" min="1" max="365" defaultValue="1" required/></Field></div><Field label="Valor unitário (R$)"><input name={'rate'+i} type="number" min="0.01" step="0.01" required/></Field></fieldset>)}<Field label="Condições comerciais"><textarea name="terms" maxLength={3000} placeholder="Datas da estadia, refeições incluídas, pagamento e cancelamento"/></Field></>}
 {['order','proposal'].includes(modal)&&<div className="inline-actions"><button className="secondary" type="button" disabled={lineCount>=30} onClick={()=>setLineCount(v=>v+1)}>Adicionar item</button>{lineCount>1&&<button className="text-link" type="button" onClick={()=>setLineCount(v=>v-1)}>Remover último item</button>}</div>}
 {modal==='open_shift'&&<Field label="Fundo inicial em dinheiro (R$)"><input name="opening" type="number" min="0" step="0.01" defaultValue="0" required/></Field>}
 {modal==='close_shift'&&<><p>Saldo esperado: <strong>{money(shift?.live_expected??0)}</strong></p><Field label="Valor contado em dinheiro (R$)"><input name="counted" type="number" min="0" step="0.01" required/></Field><Field label="Observações da conferência"><textarea name="notes" maxLength={1000}/></Field></>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal('')}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div></form></DialogContent></Dialog></>;
}
