import {useCallback,useEffect,useState} from 'react';
import {apiFetch} from '@/lib/client';
import type {HotelData} from '@/lib/hotel-domain';
import {shortDay} from '@/lib/hotel-domain';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {toast} from 'sonner';
type Request={id:string;name:string;phone:string;checkin:string;checkout:string;category:string;guests:number;notes:string;status:string};
export default function SiteRequests({data,onChanged}:{data:HotelData;onChanged:()=>void}){const [requests,setRequests]=useState<Request[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rooms,setRooms]=useState<Record<string,string>>({});const hid=data.hotel!.id;
const refresh=useCallback(async()=>{try{const r=await apiFetch('/requests?hotel='+encodeURIComponent(hid));const d=await r.json();if(!r.ok)throw new Error(d.error);setRequests(d.requests);setError('')}catch(e){setError((e as Error).message)}},[hid]);useEffect(()=>{void refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[refresh]);
const update=async(id:string,status:string)=>{setBusy(true);try{const r=await apiFetch('/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status,hotel:hid,room:rooms[id]})});const d=await r.json();if(!r.ok)throw new Error(d.error);toast.success(d.message);await refresh();onChanged()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
return <section className="panel"><div className="panel-heading"><div><h2>Solicitações recebidas pelo site</h2><p>Escolha um quarto para confirmar. A reserva aparecerá no mapa e na recepção.</p></div><button className="secondary" onClick={refresh}>Atualizar</button></div>{error&&<p role="alert">{error}</p>}<Table><TableHeader><TableRow>{['Hóspede','Período','Acomodação','Situação','Quarto / ação'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{requests.map(r=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><small>{r.phone}</small><small>{r.notes}</small></TableCell><TableCell>{shortDay(r.checkin)} a {shortDay(r.checkout)}<small>{r.guests} hóspedes</small></TableCell><TableCell>{r.category}</TableCell><TableCell>{({pending:'Aguardando confirmação',confirmed:'Confirmada',cancelled:'Cancelada'} as Record<string,string>)[r.status]}</TableCell><TableCell>{r.status==='pending'&&<div className="request-actions"><Select value={rooms[r.id]??''} onValueChange={v=>setRooms(old=>({...old,[r.id]:v}))}><SelectTrigger><SelectValue placeholder="Escolher quarto"/></SelectTrigger><SelectContent>{data.rooms.filter(q=>q.capacity>=r.guests&&q.state!=='blocked'&&!data.reservations.some(b=>b.room_id===q.id&&['confirmed','checked_in'].includes(b.status)&&b.checkin<r.checkout&&b.checkout>r.checkin)).map(q=><SelectItem key={q.id} value={q.id}>{q.number} · {q.category}</SelectItem>)}</SelectContent></Select><button className="primary" disabled={busy||!rooms[r.id]} onClick={()=>update(r.id,'confirmed')}>Confirmar</button><button className="text-link" disabled={busy} onClick={()=>update(r.id,'cancelled')}>Cancelar</button></div>}</TableCell></TableRow>)}{!requests.length&&<TableRow><TableCell colSpan={5}>As próximas solicitações do site aparecerão aqui.</TableCell></TableRow>}</TableBody></Table><p className="panel-padding muted">Grupos que precisam de vários quartos devem ser atendidos pela recepção e cadastrados por quarto. A confirmação não envia mensagem automaticamente ao hóspede.</p></section>}
