import { z } from 'npm:zod@3.25.76';
import { today, addDays, bookingTotal, cents, validDay } from './hotel-domain.ts';
export async function handle(req:Request,user:{id:string;email?:string},db:any){
const headers=async()=>new Headers({'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email??user.id});const hotelDb=()=>db;

const str=(v:unknown,max=200)=>z.string().trim().min(1,'Preencha os campos obrigatórios.').max(max).parse(v);
const optional=(v:unknown,max=1000)=>z.string().max(max).parse(v??'').trim();
const id=()=>crypto.randomUUID();
async function identity(){const h=await headers();const uid=h.get('oai-authenticated-user-id');if(!uid)throw new Error('UNAUTHORIZED');return {uid,email:h.get('oai-authenticated-user-email')??uid};}
function errorResponse(e:unknown){const s=e instanceof Error?e.message:'';if(s==='UNAUTHORIZED')return Response.json({error:'Entre na sua conta para continuar.'},{status:401});if(s==='FORBIDDEN')return Response.json({error:'Você não tem acesso a este hotel.'},{status:403});if(e instanceof z.ZodError)return Response.json({error:e.issues[0]?.message??'Revise os campos.'},{status:400});
const known=['CONFLITO','CAPACIDADE','QUARTO','SALDO','RECEBIMENTO','VINCULO','FECHADA','ESTADO'];if(known.some(x=>s.includes(x))){const map:Record<string,string>={CONFLITO:'Este quarto já possui reserva no período. Escolha outro quarto ou outras datas.',CAPACIDADE:'A capacidade do quarto deve comportar os hóspedes das reservas ativas.',QUARTO:'Quarto indisponível. Confira a limpeza, manutenção e ocupação.',SALDO:'Quite o saldo antes do check-out. Para cancelar, devolva primeiro os valores recebidos.',RECEBIMENTO:'O valor excede o saldo permitido ou este lançamento já foi registrado.',VINCULO:'O registro não pertence a este hotel.',FECHADA:'Esta conta já foi encerrada.',ESTADO:'A situação foi alterada. Atualize os dados e tente novamente.'};return Response.json({error:map[known.find(x=>s.includes(x))!]},{status:409});}
if(s.includes('UNIQUE constraint')||s.includes('duplicate key'))return Response.json({error:'Este registro já existe. Atualize a página para conferir.'},{status:409});if(s.startsWith('PG_')||s.startsWith('D1_')||s.includes('SQLITE')||s==='Banco indisponível'){console.error('hotel-storage',s);return Response.json({error:'Não foi possível acessar os dados. Tente novamente em instantes.'},{status:503});}return Response.json({error:s||'Não foi possível concluir. Tente novamente.'},{status:400});}
async function GET(request:Request){try{const {uid,email}=await identity();const db=hotelDb();const hs=await db.prepare('SELECT id,name,demo FROM hotels WHERE owner=? ORDER BY created,id').bind(uid).all();const hotels=hs.results;const selected=new URL(request.url).searchParams.get('hotel')??String(hotels[0]?.id??'');if(!selected)return Response.json({hotels,hotel:null,rooms:[],reservations:[],entries:[],audit:[],user:email,today:today()},{headers:{'Cache-Control':'no-store'}});const hotel=hotels.find(h=>h.id===selected);if(!hotel)throw new Error('FORBIDDEN');const result=await db.batch([db.prepare('SELECT * FROM rooms WHERE hotel_id=? ORDER BY floor,number').bind(selected),db.prepare('SELECT * FROM reservations WHERE hotel_id=? ORDER BY checkin DESC,created DESC').bind(selected),db.prepare('SELECT * FROM entries WHERE hotel_id=? ORDER BY created DESC,id').bind(selected),db.prepare('SELECT * FROM audit WHERE hotel_id=? ORDER BY id DESC LIMIT 50').bind(selected)]);return Response.json({hotels,hotel,rooms:result[0].results,reservations:result[1].results,entries:result[2].results,audit:result[3].results,user:email,today:today()},{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
async function POST(request:Request){try{const {uid,email}=await identity();if(!request.headers.get('content-type')?.includes('application/json'))return Response.json({error:'Formato inválido.'},{status:415});const b=await request.json() as Record<string,unknown>;const action=str(b.action);const db=hotelDb();const now=new Date().toISOString();
if(action==='demo'||action==='hotel'){let hid=id();if(action==='demo'){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(uid));hid='demo-'+Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,'0')).join('').slice(0,32);const prior=await db.prepare('SELECT id FROM hotels WHERE id=? AND owner=?').bind(hid,uid).first();if(prior)return Response.json({id:hid});}
const stmts=[db.prepare('INSERT INTO hotels (id,owner,name,demo,created) VALUES (?,?,?,?,?)').bind(hid,uid,action==='demo'?'Teles Plaza Hotel':str(b.name,100),action==='demo'?1:0,now)];if(action==='demo'){
const types=['Casal','Duplo','Triplo'];for(let i=0;i<16;i++){const category=types[i%3];stmts.push(db.prepare('INSERT INTO rooms (id,hotel_id,number,category,capacity,rate,state,floor) VALUES (?,?,?,?,?,?,?,?)').bind(hid+'-room-'+i,hid,String((i<8?100:200)+(i%8)+1),category,category==='Triplo'?3:2,category==='Triplo'?29000:category==='Duplo'?24000:22000,i===14?'dirty':i===15?'blocked':'clean',i<8?'1':'2'));}
const names=['Mariana Oliveira','Carlos Mendes','Ana Beatriz Costa','Rafael Almeida','Fernanda Lima','Pedro Henrique','Juliana Santos','Lucas Ferreira','Camila Rodrigues','Bruno Carvalho'];for(let i=0;i<10;i++){const rid=hid+'-res-'+i;const start=addDays(today(),i<6?-2:i<8?0:2);const end=addDays(today(),i<2?0:i<6?2:i<8?3:5);const rate=i%3===2?29000:i%3===1?24000:22000;const total=bookingTotal(start,end,rate);stmts.push(db.prepare('INSERT INTO reservations (id,hotel_id,room_id,name,phone,company,guests,checkin,checkout,rate,total,status,source,notes,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,hid,hid+'-room-'+i,names[i],'',i===1?'Empresa Exemplo':'',2,start,end,rate,total,i<6?'checked_in':'confirmed',i%2?'WhatsApp':'Recepção','Registro fictício para demonstração.',now));stmts.push(db.prepare('INSERT INTO entries (id,hotel_id,reservation_id,kind,amount,description,method,due,paid,created,actor) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id(),hid,rid,'payment',i<2?total:Math.round(total/2),'Sinal da hospedagem','Pix',today(),1,now,email));}
for(const [name,amount,paid] of [['Lavanderia',32000,1],['Fornecedor de alimentos',86000,0],['Material de limpeza',18500,1]] as const)stmts.push(db.prepare('INSERT INTO entries (id,hotel_id,kind,amount,description,method,due,paid,created,actor) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id(),hid,'expense',amount,name,'Pix',today(),paid,now,email));}
await db.batch(stmts);return Response.json({id:hid});}
const hid=str(b.hotel);const hotel=await db.prepare('SELECT id FROM hotels WHERE id=? AND owner=?').bind(hid,uid).first();if(!hotel)throw new Error('FORBIDDEN');let entity='';let label='';const statements=[];
const guards:string[]=[];
const guard=(column:'room'|'capacity'|'overlap'|'state'|'balance'|'receipt',expression:string,values:(string|number|null)[])=>{const key=id();guards.push(key);statements.push(db.prepare('INSERT INTO operation_guards (id,'+column+') VALUES (?,CASE WHEN ('+expression+') THEN 1 ELSE 0 END)').bind(key,...values));};

const cashShift=async(method:string,paid:number)=>{if(method!=='Dinheiro'||!paid)return null;const shift=await db.prepare('SELECT id FROM cash_shifts WHERE hotel_id=? AND closed IS NULL').bind(hid).first();if(!shift)throw new Error('Abra o caixa antes de registrar pagamentos em dinheiro.');guard('state','EXISTS(SELECT 1 FROM cash_shifts WHERE id=? AND hotel_id=? AND closed IS NULL)',[String(shift.id),hid]);return String(shift.id);};

if(action==='room'){entity=id();const category=z.enum(['Casal','Duplo','Triplo','Individual','Suíte','Duplo / Triplo','Casal com cama auxiliar']).parse(b.category);statements.push(db.prepare('INSERT INTO rooms (id,hotel_id,number,category,capacity,rate,state,floor,extra_guest_rate) VALUES (?,?,?,?,?,?,?,?,?)').bind(entity,hid,str(b.number,12),category,z.coerce.number().int().min(1).max(10).parse(b.capacity),cents(b.rate),'clean',str(b.floor,20),Math.round(z.coerce.number().min(0).max(10000000).parse(b.extra_guest_rate??0)*100)));label='Quarto cadastrado';}
else if(action==='room_update'){entity=str(b.id);const category=z.enum(['Casal','Duplo','Triplo','Individual','Suíte','Duplo / Triplo','Casal com cama auxiliar']).parse(b.category);const capacity=z.coerce.number().int().min(1).max(10).parse(b.capacity);const room=await db.prepare('SELECT * FROM rooms WHERE id=? AND hotel_id=?').bind(entity,hid).first();if(!room)throw new Error('VINCULO');guard('capacity',"NOT EXISTS(SELECT 1 FROM reservations WHERE room_id=? AND hotel_id=? AND status IN ('confirmed','checked_in') AND guests>?)",[entity,hid,capacity]);statements.push(db.prepare('UPDATE rooms SET number=?,category=?,capacity=?,rate=?,floor=?,extra_guest_rate=? WHERE id=? AND hotel_id=?').bind(str(b.number,12),category,capacity,cents(b.rate),str(b.floor,20),Math.round(z.coerce.number().min(0).max(10000000).parse(b.extra_guest_rate??Number(room.extra_guest_rate??0)/100)*100),entity,hid));label='Quarto atualizado';}
else if(action==='room_state'){entity=str(b.id);const state=z.enum(['clean','dirty','cleaning','blocked']).parse(b.state);const room=await db.prepare('SELECT id FROM rooms WHERE id=? AND hotel_id=?').bind(entity,hid).first();if(!room)throw new Error('VINCULO');if(state==='blocked')guard('room',"NOT EXISTS(SELECT 1 FROM reservations WHERE room_id=? AND hotel_id=? AND status IN ('confirmed','checked_in'))",[entity,hid]);statements.push(db.prepare('UPDATE rooms SET state=? WHERE id=? AND hotel_id=?').bind(state,entity,hid));label='Quarto: '+({clean:'liberado',dirty:'aguardando limpeza',cleaning:'em limpeza',blocked:'em manutenção'}[state]);}
else if(action==='reservation'){entity=str(b.id);const rid=str(b.room);const room=await db.prepare('SELECT * FROM rooms WHERE id=? AND hotel_id=?').bind(rid,hid).first();if(!room)throw new Error('VINCULO');const start=str(b.checkin),end=str(b.checkout);if(start<today())throw new Error('A entrada não pode ser anterior a hoje.');const rate=cents(b.rate);const total=bookingTotal(start,end,rate);
guard('room',"EXISTS(SELECT 1 FROM rooms WHERE id=? AND hotel_id=? AND state!='blocked')",[rid,hid]);
guard('capacity',"? <= (SELECT capacity FROM rooms WHERE id=? AND hotel_id=?)",[z.coerce.number().int().min(1).max(10).parse(b.guests),rid,hid]);
guard('overlap',"NOT EXISTS(SELECT 1 FROM reservations WHERE room_id=? AND hotel_id=? AND status IN ('confirmed','checked_in') AND checkin<? AND checkout>?)",[rid,hid,end,start]);
statements.push(db.prepare('INSERT INTO reservations (id,hotel_id,room_id,name,phone,company,guests,checkin,checkout,rate,total,status,source,notes,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(entity,hid,rid,str(b.name,120),optional(b.phone,30),optional(b.company,150),z.coerce.number().int().min(1).max(10).parse(b.guests),start,end,rate,total,'confirmed',z.enum(['Recepção','WhatsApp','Site','Empresa','Agência']).parse(b.source),optional(b.notes),now));label='Reserva criada';}
else if(action==='status'){entity=str(b.id);const status=z.enum(['checked_in','checked_out','cancelled']).parse(b.status);const r=await db.prepare('SELECT * FROM reservations WHERE id=? AND hotel_id=?').bind(entity,hid).first();if(!r)throw new Error('VINCULO');if(status==='checked_in'&&(String(r.checkin)>today()||String(r.checkout)<=today()))throw new Error('O check-in deve ocorrer dentro do período reservado.');guard('state',"EXISTS(SELECT 1 FROM reservations WHERE id=? AND hotel_id=? AND status=?)",[entity,hid,status==='checked_out'?'checked_in':'confirmed']);
if(status==='checked_in')guard('room',"EXISTS(SELECT 1 FROM rooms WHERE id=? AND hotel_id=? AND state='clean') AND NOT EXISTS(SELECT 1 FROM reservations WHERE room_id=? AND hotel_id=? AND status='checked_in')",[String(r.room_id),hid,String(r.room_id),hid]);
if(status==='checked_out')guard('balance',"(SELECT total FROM reservations WHERE id=? AND hotel_id=?)+COALESCE((SELECT SUM(CASE kind WHEN 'charge' THEN amount WHEN 'payment' THEN -amount WHEN 'refund' THEN amount ELSE 0 END) FROM entries WHERE reservation_id=? AND hotel_id=?),0)=0",[entity,hid,entity,hid]);
if(status==='cancelled')guard('balance',"COALESCE((SELECT SUM(CASE kind WHEN 'payment' THEN amount WHEN 'refund' THEN -amount ELSE 0 END) FROM entries WHERE reservation_id=? AND hotel_id=?),0)=0",[entity,hid]);
statements.push(db.prepare('UPDATE reservations SET status=? WHERE id=? AND hotel_id=?').bind(status,entity,hid));if(status==='checked_out')statements.push(db.prepare("UPDATE rooms SET state='dirty' WHERE id=? AND hotel_id=?").bind(r.room_id,hid));label=({checked_in:'Check-in realizado',checked_out:'Check-out realizado',cancelled:'Reserva cancelada'})[status];}
else if(action==='entry'){entity=str(b.id);const kind=z.enum(['charge','payment','refund','expense']).parse(b.kind);const rid=kind==='expense'?null:str(b.reservation);if(rid){const r=await db.prepare('SELECT id FROM reservations WHERE id=? AND hotel_id=?').bind(rid,hid).first();if(!r)throw new Error('VINCULO');}const due=str(b.due);if(!validDay(due))throw new Error('Informe uma data válida.');const method=kind==='charge'?'':z.enum(['Pix','Dinheiro','Cartão de crédito','Cartão de débito','Transferência']).parse(b.method);if(rid)guard('state',"EXISTS(SELECT 1 FROM reservations WHERE id=? AND hotel_id=? AND status IN ('confirmed','checked_in'))",[rid,hid]);
if(kind==='payment')guard('receipt',"? <= (SELECT total FROM reservations WHERE id=? AND hotel_id=?)+COALESCE((SELECT SUM(CASE kind WHEN 'charge' THEN amount WHEN 'payment' THEN -amount WHEN 'refund' THEN amount ELSE 0 END) FROM entries WHERE reservation_id=? AND hotel_id=?),0)",[cents(b.amount),rid,hid,rid,hid]);
if(kind==='refund')guard('receipt',"? <= COALESCE((SELECT SUM(CASE kind WHEN 'payment' THEN amount WHEN 'refund' THEN -amount ELSE 0 END) FROM entries WHERE reservation_id=? AND hotel_id=?),0)",[cents(b.amount),rid,hid]);
const paid=kind==='expense'?z.coerce.number().int().min(0).max(1).parse(b.paid):1;const shift=await cashShift(method,paid);statements.push(db.prepare('INSERT INTO entries (id,hotel_id,reservation_id,kind,amount,description,method,due,paid,created,actor,shift_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(entity,hid,rid,kind,cents(b.amount),str(b.description,200),method,due,paid,now,email,shift));label=({charge:'Consumo lançado',payment:'Recebimento registrado',refund:'Devolução registrada',expense:'Despesa lançada'})[kind];}
else if(action==='pay_expense'){entity=str(b.id);const e=await db.prepare('SELECT * FROM entries WHERE id=? AND hotel_id=? AND kind=?').bind(entity,hid,'expense').first();if(!e)throw new Error('VINCULO');if(e.paid)throw new Error('Despesa já paga.');guard('state',"EXISTS(SELECT 1 FROM entries WHERE id=? AND hotel_id=? AND paid=0 AND kind='expense')",[entity,hid]);const shift=await cashShift(String(e.method),1);statements.push(db.prepare('UPDATE entries SET paid=1,due=?,shift_id=? WHERE id=? AND hotel_id=? AND paid=0').bind(today(),shift,entity,hid));label='Despesa paga';}
else throw new Error('Ação desconhecida.');
statements.push(db.prepare('INSERT INTO audit (hotel_id,actor,action,entity,created) VALUES (?,?,?,?,?)').bind(hid,email,label,entity,now));for(const key of guards)statements.push(db.prepare('DELETE FROM operation_guards WHERE id=?').bind(key));await db.batch(statements);return Response.json({id:entity,message:label});}catch(e){return errorResponse(e);}}
return req.method==='GET'?GET(req):POST(req);
}
