import {z} from 'npm:zod@3.25.76';
import {cents,today} from './hotel-domain.ts';
import {quantity,proposalLines,date} from './operations-domain.ts';
export async function handle(req:Request,user:{id:string;email?:string},db:any){
const headers=async()=>new Headers({'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email??user.id});const hotelDb=()=>db;

const text=(v:unknown,max=200)=>z.string().trim().min(1).max(max).parse(v);
const optional=(v:unknown,max=1000)=>z.string().max(max).parse(v??'').trim();
async function identity(hotel:string){const h=await headers(),user=h.get('oai-authenticated-user-id');if(!user)throw new Error('UNAUTHORIZED');const db=hotelDb();const own=await db.prepare('SELECT id FROM hotels WHERE id=? AND owner=?').bind(hotel,user).first();if(!own)throw new Error('FORBIDDEN');return{db,actor:h.get('oai-authenticated-user-email')??user};}
function fail(e:unknown){const m=e instanceof Error?e.message:'Falha ao salvar.';let status=400,message=m;if(m==='UNAUTHORIZED'){status=401;message='Entre na sua conta.';}else if(m==='FORBIDDEN'){status=403;message='Unidade sem acesso.';}else if(/ESTOQUE/.test(m)){status=409;message='Estoque insuficiente para esta saída.';}else if(/ESTADO|UNIQUE constraint|duplicate key/.test(m)){status=409;message='Este registro já foi processado ou sua situação mudou. Atualize os dados.';}else if(/SQLITE|D1_|CHECK constraint/.test(m)){status=503;message='Não foi possível concluir a operação. Tente novamente.';console.error('operations',m);}else if(e instanceof z.ZodError){message='Revise os campos obrigatórios e os valores informados.';}return Response.json({error:message},{status});}
async function GET(req:Request){try{const hid=text(new URL(req.url).searchParams.get('hotel'));const {db}=await identity(hid);const result=await db.batch<Record<string,unknown>>([db.prepare('SELECT * FROM products WHERE hotel_id=? ORDER BY name').bind(hid),db.prepare('SELECT * FROM suppliers WHERE hotel_id=? ORDER BY name').bind(hid),db.prepare('SELECT * FROM purchase_orders WHERE hotel_id=? ORDER BY created DESC').bind(hid),db.prepare('SELECT * FROM proposals WHERE hotel_id=? ORDER BY created DESC').bind(hid),db.prepare('SELECT * FROM stock_movements WHERE hotel_id=? ORDER BY created DESC LIMIT 200').bind(hid),db.prepare("SELECT s.*,s.opening+COALESCE((SELECT SUM(CASE e.kind WHEN 'payment' THEN e.amount WHEN 'refund' THEN -e.amount WHEN 'expense' THEN -e.amount ELSE 0 END) FROM entries e WHERE e.shift_id=s.id AND e.hotel_id=s.hotel_id AND e.method='Dinheiro' AND e.paid=1),0) AS live_expected FROM cash_shifts s WHERE s.hotel_id=? ORDER BY s.opened DESC LIMIT 100").bind(hid)]);return Response.json({products:result[0].results,suppliers:result[1].results,orders:result[2].results.map(r=>({...r,items:JSON.parse(String(r.items))})),proposals:result[3].results.map(r=>({...r,items:JSON.parse(String(r.items))})),movements:result[4].results,shifts:result[5].results},{headers:{'Cache-Control':'no-store'}});}catch(e){return fail(e);}}
async function POST(req:Request){try{if(!req.headers.get('content-type')?.includes('application/json'))return Response.json({error:'Formato inválido.'},{status:415});const b=await req.json() as Record<string,unknown>;const hid=text(b.hotel),{db,actor}=await identity(hid),action=text(b.action),id=text(b.id),now=new Date().toISOString();const statements=[];const checks:string[]=[];let message='Salvo.';
const guard=(expression:string,values:(string|number)[])=>{const key=crypto.randomUUID();checks.push(key);statements.push(db.prepare('INSERT INTO operation_guards (id,state) VALUES (?,CASE WHEN ('+expression+') THEN 1 ELSE 0 END)').bind(key,...values));};
if(action==='supplier'){statements.push(db.prepare('INSERT INTO suppliers (id,hotel_id,name,document,contact,notes,created) VALUES (?,?,?,?,?,?,?)').bind(id,hid,text(b.name),optional(b.document,30),optional(b.contact,150),optional(b.notes),now));message='Fornecedor cadastrado.';}
else if(action==='product'){const minimum=Number(b.minimum??0);if(!Number.isFinite(minimum)||minimum<0||minimum>1000000)throw new Error('Estoque mínimo inválido.');statements.push(db.prepare('INSERT INTO products (id,hotel_id,name,unit,category,quantity,minimum,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,hid,text(b.name),z.enum(['un','kg','L','pacote','caixa']).parse(b.unit),z.enum(['Alimentação','Limpeza','Frigobar','Enxoval','Manutenção','Outros']).parse(b.category),0,Math.round(minimum*1000),now));message='Produto cadastrado.';}
else if(action==='stock'){const product=text(b.product),q=quantity(b.quantity)*(b.kind==='out'?-1:1);z.enum(['in','out']).parse(b.kind);guard('EXISTS(SELECT 1 FROM products WHERE id=? AND hotel_id=?)',[product,hid]);statements.push(db.prepare('UPDATE products SET quantity=quantity+? WHERE id=? AND hotel_id=?').bind(q,product,hid));statements.push(db.prepare('INSERT INTO stock_movements (id,hotel_id,product_id,quantity,reason,created,actor) VALUES (?,?,?,?,?,?,?)').bind(id,hid,product,q,text(b.reason),now,actor));message=q>0?'Entrada de estoque registrada.':'Saída de estoque registrada.';}
else if(action==='order'){const supplier=text(b.supplier);const lines=z.array(z.object({product:z.string(),quantity:z.union([z.number(),z.string()]),rate:z.union([z.number(),z.string()])})).min(1).max(30).parse(b.items);if(new Set(lines.map(l=>l.product)).size!==lines.length)throw new Error('Agrupe quantidades do mesmo produto em uma linha.');guard('EXISTS(SELECT 1 FROM suppliers WHERE id=? AND hotel_id=?)',[supplier,hid]);const items=[];for(const l of lines){const p=await db.prepare('SELECT name,unit FROM products WHERE id=? AND hotel_id=?').bind(l.product,hid).first();if(!p)throw new Error('Produto não pertence a esta unidade.');const q=quantity(l.quantity),rate=cents(l.rate);const total=Math.round(q*rate/1000);if(total<1)throw new Error('O total de cada item deve ser pelo menos R$ 0,01.');items.push({product:l.product,name:p.name,unit:p.unit,quantity:q,rate,total});}const total=items.reduce((s,l)=>s+l.total,0);if(total>1000000000)throw new Error('Pedido acima do limite de R$ 10 milhões.');statements.push(db.prepare('INSERT INTO purchase_orders (id,hotel_id,supplier_id,items,total,status,due,notes,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,hid,supplier,JSON.stringify(items),total,'pending',date(b.due),optional(b.notes),now));message='Pedido de compra criado.';}
else if(action==='order_status'){const status=z.enum(['approved','received','cancelled']).parse(b.status);const order=await db.prepare('SELECT * FROM purchase_orders WHERE id=? AND hotel_id=?').bind(id,hid).first();if(!order)throw new Error('Pedido não encontrado.');guard("EXISTS(SELECT 1 FROM purchase_orders WHERE id=? AND hotel_id=? AND status=?)",[id,hid,status==='received'?'approved':'pending']);if(status==='received'){const items=JSON.parse(String(order.items)) as {product:string;quantity:number}[];for(const line of items){guard('EXISTS(SELECT 1 FROM products WHERE id=? AND hotel_id=?)',[line.product,hid]);statements.push(db.prepare('UPDATE products SET quantity=quantity+? WHERE id=? AND hotel_id=?').bind(line.quantity,line.product,hid));statements.push(db.prepare('INSERT INTO stock_movements (id,hotel_id,product_id,quantity,reason,order_id,created,actor) VALUES (?,?,?,?,?,?,?,?)').bind(id+'-'+line.product,hid,line.product,line.quantity,'Recebimento de compra',id,now,actor));}statements.push(db.prepare('INSERT INTO entries (id,hotel_id,kind,amount,description,method,due,paid,created,actor) VALUES (?,?,?,?,?,?,?,?,?,?)').bind('order-'+id,hid,'expense',order.total,'Compra '+id.slice(0,8),'Transferência',order.due,0,now,actor));}statements.push(db.prepare('UPDATE purchase_orders SET status=? WHERE id=? AND hotel_id=?').bind(status,id,hid));message=status==='received'?'Mercadoria recebida: estoque e conta a pagar atualizados.':status==='approved'?'Compra aprovada.':'Compra cancelada.';}
else if(action==='proposal'){const items=proposalLines(b.items),total=items.reduce((s,l)=>s+l.total,0);if(total>1000000000)throw new Error('Proposta acima do limite de R$ 10 milhões.');const validity=date(b.validUntil);if(validity<today())throw new Error('A validade não pode estar no passado.');statements.push(db.prepare('INSERT INTO proposals (id,hotel_id,client,contact,items,total,status,valid_until,terms,created) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,hid,text(b.client),optional(b.contact,150),JSON.stringify(items),total,'draft',validity,optional(b.terms,3000),now));message='Proposta salva.';}
else if(action==='proposal_status'){const status=z.enum(['sent','approved','cancelled']).parse(b.status);guard("EXISTS(SELECT 1 FROM proposals WHERE id=? AND hotel_id=? AND status IN ('draft','sent'))",[id,hid]);statements.push(db.prepare('UPDATE proposals SET status=? WHERE id=? AND hotel_id=?').bind(status,id,hid));message='Situação da proposta atualizada.';}
else if(action==='open_shift'){const opening=Number(b.opening);if(!Number.isFinite(opening)||opening<0||opening>10000000)throw new Error('Fundo de caixa inválido.');statements.push(db.prepare('INSERT INTO cash_shifts (id,hotel_id,actor,opening,opened) VALUES (?,?,?,?,?)').bind(id,hid,actor,Math.round(opening*100),now));message='Caixa aberto.';}
else if(action==='close_shift'){const counted=Number(b.counted);if(!Number.isFinite(counted)||counted<0||counted>10000000)throw new Error('Valor contado inválido.');guard('EXISTS(SELECT 1 FROM cash_shifts WHERE id=? AND hotel_id=? AND closed IS NULL)',[id,hid]);statements.push(db.prepare("UPDATE cash_shifts SET closed=?,counted=?,notes=?,expected=opening+COALESCE((SELECT SUM(CASE e.kind WHEN 'payment' THEN e.amount WHEN 'refund' THEN -e.amount WHEN 'expense' THEN -e.amount ELSE 0 END) FROM entries e WHERE e.shift_id=cash_shifts.id AND e.hotel_id=cash_shifts.hotel_id AND e.method='Dinheiro' AND e.paid=1),0) WHERE id=? AND hotel_id=? AND closed IS NULL").bind(now,Math.round(counted*100),optional(b.notes),id,hid));message='Caixa fechado. Conferência registrada.';}
else throw new Error('Ação inválida.');statements.push(db.prepare('INSERT INTO audit (hotel_id,actor,action,entity,created) VALUES (?,?,?,?,?)').bind(hid,actor,message,id,now));for(const key of checks)statements.push(db.prepare('DELETE FROM operation_guards WHERE id=?').bind(key));await db.batch(statements);return Response.json({id,message});}catch(e){return fail(e);}}
return req.method==='GET'?GET(req):POST(req);
}
