CREATE SCHEMA teles;

REVOKE ALL ON SCHEMA teles FROM PUBLIC, anon, authenticated;

SET search_path TO teles, public;

CREATE TABLE "hotels" (
	"id" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"demo" integer DEFAULT 0 NOT NULL,
	"created" text NOT NULL
);

ALTER TABLE teles.hotels ENABLE ROW LEVEL SECURITY;

CREATE TABLE "rooms" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"number" text NOT NULL,
	"category" text NOT NULL,
	"capacity" integer NOT NULL,
	"rate" integer NOT NULL,
	"state" text DEFAULT 'clean' NOT NULL,
	"floor" text DEFAULT '1' NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.rooms ENABLE ROW LEVEL SECURITY;

CREATE TABLE "reservations" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"room_id" text NOT NULL,
	"name" text NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"company" text DEFAULT '' NOT NULL,
	"guests" integer NOT NULL,
	"checkin" text NOT NULL,
	"checkout" text NOT NULL,
	"rate" integer NOT NULL,
	"total" integer NOT NULL,
	"status" text DEFAULT 'confirmed' NOT NULL,
	"source" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.reservations ENABLE ROW LEVEL SECURITY;

CREATE TABLE "cash_shifts" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"actor" text NOT NULL,
	"opening" integer NOT NULL,
	"opened" text NOT NULL,
	"closed" text,
	"expected" integer,
	"counted" integer,
	"notes" text DEFAULT '' NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.cash_shifts ENABLE ROW LEVEL SECURITY;

CREATE TABLE "entries" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"reservation_id" text,
	"kind" text NOT NULL,
	"amount" integer NOT NULL,
	"description" text NOT NULL,
	"method" text DEFAULT '' NOT NULL,
	"due" text NOT NULL,
	"paid" integer DEFAULT 1 NOT NULL,
	"created" text NOT NULL,
	"actor" text NOT NULL, "shift_id" text,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.entries ENABLE ROW LEVEL SECURITY;

CREATE TABLE "audit" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
	"hotel_id" text NOT NULL,
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.audit ENABLE ROW LEVEL SECURITY;

CREATE TABLE "operation_guards" (
	"id" text PRIMARY KEY NOT NULL,
	"room" integer DEFAULT 1 NOT NULL,
	"capacity" integer DEFAULT 1 NOT NULL,
	"overlap" integer DEFAULT 1 NOT NULL,
	"state" integer DEFAULT 1 NOT NULL,
	"balance" integer DEFAULT 1 NOT NULL,
	"receipt" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "QUARTO" CHECK("operation_guards"."room"=1),
	CONSTRAINT "CAPACIDADE" CHECK("operation_guards"."capacity"=1),
	CONSTRAINT "CONFLITO" CHECK("operation_guards"."overlap"=1),
	CONSTRAINT "ESTADO" CHECK("operation_guards"."state"=1),
	CONSTRAINT "SALDO" CHECK("operation_guards"."balance"=1),
	CONSTRAINT "RECEBIMENTO" CHECK("operation_guards"."receipt"=1)
);

ALTER TABLE teles.operation_guards ENABLE ROW LEVEL SECURITY;

CREATE TABLE "suppliers" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"name" text NOT NULL,
	"document" text DEFAULT '' NOT NULL,
	"contact" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.suppliers ENABLE ROW LEVEL SECURITY;

CREATE TABLE "products" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"name" text NOT NULL,
	"unit" text NOT NULL,
	"category" text NOT NULL,
	"quantity" integer DEFAULT 0 NOT NULL,
	"minimum" integer DEFAULT 0 NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ESTOQUE" CHECK("products"."quantity">=0)
);

ALTER TABLE teles.products ENABLE ROW LEVEL SECURITY;

CREATE TABLE "purchase_orders" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"supplier_id" text NOT NULL,
	"items" text NOT NULL,
	"total" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"due" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE TABLE "stock_movements" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"product_id" text NOT NULL,
	"quantity" integer NOT NULL,
	"reason" text NOT NULL,
	"order_id" text,
	"created" text NOT NULL,
	"actor" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("product_id") REFERENCES "products"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.stock_movements ENABLE ROW LEVEL SECURITY;

CREATE TABLE "proposals" (
	"id" text PRIMARY KEY NOT NULL,
	"hotel_id" text NOT NULL,
	"client" text NOT NULL,
	"contact" text DEFAULT '' NOT NULL,
	"items" text NOT NULL,
	"total" integer NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"valid_until" text NOT NULL,
	"terms" text NOT NULL,
	"created" text NOT NULL,
	FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON UPDATE no action ON DELETE no action
);

ALTER TABLE teles.proposals ENABLE ROW LEVEL SECURITY;

CREATE INDEX "idx_audit_hotel" ON "audit" ("hotel_id","id");

CREATE INDEX "idx_entries_hotel_due" ON "entries" ("hotel_id","due");

CREATE INDEX "idx_entries_reservation" ON "entries" ("reservation_id");

CREATE INDEX "idx_hotels_owner" ON "hotels" ("owner");

CREATE INDEX "idx_reservations_hotel_dates" ON "reservations" ("hotel_id","checkin","checkout");

CREATE INDEX "idx_reservations_room_dates" ON "reservations" ("room_id","checkin","checkout");

CREATE UNIQUE INDEX "idx_rooms_hotel_number" ON "rooms" ("hotel_id","number");

CREATE INDEX "idx_shifts_hotel" ON "cash_shifts" ("hotel_id");

CREATE UNIQUE INDEX "idx_one_open_shift" ON "cash_shifts" ("hotel_id") WHERE "cash_shifts"."closed" IS NULL;

CREATE INDEX "idx_products_hotel" ON "products" ("hotel_id");

CREATE INDEX "idx_proposals_hotel" ON "proposals" ("hotel_id");

CREATE INDEX "idx_orders_hotel" ON "purchase_orders" ("hotel_id");

CREATE INDEX "idx_stock_hotel" ON "stock_movements" ("hotel_id");

CREATE INDEX "idx_stock_product" ON "stock_movements" ("product_id");

CREATE INDEX "idx_suppliers_hotel" ON "suppliers" ("hotel_id");

REVOKE ALL ON ALL TABLES IN SCHEMA teles FROM PUBLIC, anon, authenticated;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA teles FROM PUBLIC, anon, authenticated;
CREATE TABLE teles.operators (user_id uuid PRIMARY KEY REFERENCES auth.users(id), created timestamptz NOT NULL DEFAULT now());
CREATE TABLE teles.portal_config (id integer PRIMARY KEY CHECK(id=1),hotel_id text REFERENCES teles.hotels(id));
CREATE TABLE teles.activation (id integer PRIMARY KEY CHECK(id=1),digest text NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz);
CREATE TABLE teles.booking_requests (
 id text PRIMARY KEY, hotel_id text NOT NULL REFERENCES teles.hotels(id),name text NOT NULL,phone text NOT NULL,
 checkin text NOT NULL,checkout text NOT NULL,guests integer NOT NULL CHECK(guests BETWEEN 1 AND 50),category text NOT NULL,
 notes text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','cancelled')),
 created text NOT NULL, reservation_id text REFERENCES teles.reservations(id)
);
CREATE INDEX idx_requests_hotel ON teles.booking_requests(hotel_id,created);
CREATE TABLE teles.request_limits (key text PRIMARY KEY,window_start timestamptz NOT NULL,count integer NOT NULL);
ALTER TABLE teles.operators ENABLE ROW LEVEL SECURITY;
ALTER TABLE teles.portal_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE teles.activation ENABLE ROW LEVEL SECURITY;
ALTER TABLE teles.booking_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE teles.request_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA teles FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA teles FROM PUBLIC,anon,authenticated;
RESET search_path;
