import React,{useEffect,useState,type FormEvent} from 'react';
import {createRoot} from 'react-dom/client';
import type {Session} from '@supabase/supabase-js';
import HotelApp from './app/hotel-app';
import {supabase,apiFetch} from './lib/client';
import './app/globals.css';
function App(){const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_event,s)=>setSession(s));apiFetch('/setup').then(r=>r.json()).then(d=>setSetup(d.available===true)).catch(()=>{});return()=>data.subscription.unsubscribe()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;try{if(mode==='setup'){if(f.password!==f.confirm)throw new Error('As senhas não conferem.');const r=await apiFetch('/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(false);setMode('login');}const {error}=await supabase.auth.signInWithPassword({email:f.email,password:f.password});if(error)throw new Error('Não foi possível entrar. Confira o e-mail e a senha.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <main className="loading-page">Carregando acesso…</main>;
 if(session)return <><div className="session-bar"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>Sair</button></div><HotelApp/></>;
 return <main className="access-page"><section className="access-brand"><img src="/logo-teles.png" alt="Teles Plaza Hotel"/><h1>A operação do hotel,<br/>em um só lugar.</h1><p>Reservas, hóspedes, financeiro e equipe.</p><a href="/">Voltar ao site do hotel</a></section><section className="access-form"><div className="eyebrow">ÁREA ADMINISTRATIVA</div><h2>{mode==='setup'?'Ativar administrador':'Bem-vindo de volta'}</h2><p>{mode==='setup'?'Use o código de ativação exclusivo e defina seus dados de acesso.':'Entre com o e-mail e a senha do hotel.'}</p><form onSubmit={submit}>{mode==='setup'&&<label>Código de ativação<input name="code" required autoComplete="off"/></label>}<label>E-mail<input name="email" type="email" autoComplete="username" required/></label><label>Senha<input name="password" type="password" autoComplete={mode==='setup'?'new-password':'current-password'} minLength={mode==='setup'?12:1} required/></label>{mode==='setup'&&<label>Confirme a senha<input name="confirm" type="password" autoComplete="new-password" minLength={12} required/></label>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Aguarde…':mode==='setup'?'Ativar e entrar':'Entrar no sistema'}</button></form>{setup&&<button className="text-link" onClick={()=>{setMode(mode==='setup'?'login':'setup');setError('')}}>{mode==='setup'?'Já tenho acesso':'Primeiro acesso — ativar administrador'}</button>}<small>Acesso exclusivo a administradores autorizados.</small></section></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
